language: ruby
rvm:
  - "2.3.8"
  - "2.4.5"
  - "2.5.3"
gemfile:
  - Gemfile.3.2.mysql2
  - Gemfile.3.2.sqlite3
  - Gemfile.4.2.mysql2
  - Gemfile.4.2.pg
  - Gemfile.4.2.sqlite3
  - Gemfile.5.2.mysql2
  - Gemfile.5.2.sqlite3
  - Gemfile.5.2.pg
  - Gemfile.6.0.pg
before_script:
  - psql -c 'create database active_type_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS active_type_test;'
script: bundle exec rake spec
sudo: false
cache: bundler
notifications:
  email:
    - fail@makandra.de
matrix:
  exclude:
    - rvm: "2.4.5"
      gemfile: Gemfile.3.2.mysql2
    - rvm: "2.4.5"
      gemfile: Gemfile.3.2.sqlite3
    - rvm: "2.5.3"
      gemfile: Gemfile.3.2.mysql2
    - rvm: "2.5.3"
      gemfile: Gemfile.3.2.sqlite3
    - rvm: "2.5.3"
      gemfile: Gemfile.4.2.mysql2
    - rvm: "2.5.3"
      gemfile: Gemfile.4.2.pg
    - rvm: "2.5.3"
      gemfile: Gemfile.4.2.sqlite3
    - rvm: "2.3.8"
      gemfile: Gemfile.6.0.pg
    - rvm: "2.4.5"
      gemfile: Gemfile.6.0.pg
install:
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
